require("thebootstrap.basic")
require("thebootstrap.keys")
require("thebootstrap.plugins")
require("thebootstrap.appearance")
require("thebootstrap.colorscheme")
require("thebootstrap.abbrev")
require("thebootstrap.autocmd")
