require("thebootstrap.plugins.install")

require("thebootstrap.plugins.bufkill")
require("thebootstrap.plugins.auto-session")
require("thebootstrap.plugins.tree")
require("thebootstrap.plugins.bufferline")
require("thebootstrap.plugins.telescope")
require("thebootstrap.plugins.treesitter")
require("thebootstrap.plugins.fugitive")
require("thebootstrap.plugins.lsp-zero")
require("thebootstrap.plugins.ufo")
require("thebootstrap.plugins.indentLine")
require("thebootstrap.plugins.surround")
require("thebootstrap.plugins.autotag")
require("thebootstrap.plugins.airline")
